---
    # Perform configuration tasks

- name: Disable dnsmasq on system startup # we start it later via /etc/rc.local
  service:
    name: dnsmasq
    state: stopped
    enabled: no

- name: Disable bind9 on system startup # we start it later via /etc/rc.local
  service:
    name: bind9
    state: stopped
    enabled: no

- name: Enable port forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: Create hostapd config
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd.conf
    owner: root
    group: root
    mode: 700

- name: Create iptables script
  template:
    src: scripts/iptables_setup.sh.j2
    dest: /usr/local/sbin/iptables_setup.sh
    owner: root
    group: root
    mode: 700

- name: Create rc.local script
  template:
    src: scripts/rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 700

- name: Create network interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: Exclude wlan0 as DHCP client
  lineinfile:
    dest: /etc/dhcpcd.conf
    line: 'denyinterfaces wlan0'
  ignore_errors: true # File may not exist (if dhcpcd was not installed)

- name: Create Wifi DHCP/Gateway server configuration
  template:
    src: dnsmasq.wlan0.conf.j2
    dest: /etc/dnsmasq.wlan0.conf
    owner: root
    group: root
    mode: 600

- name: Create cable Gateway server configuration
  when: cable_ip_address is defined
  template:
    src: dnsmasq.eth0.conf.j2
    dest: /etc/dnsmasq.eth0.conf
    owner: root
    group: root
    mode: 600

- name: Create the VPN configurations
  copy:
    src: openvpn/
    dest: /etc/openvpn
    owner: root
    group: root
    directory_mode: 700

- name: Create the VPN credentials file
  template:
    src: auth.txt.j2
    dest: /etc/openvpn/auth.txt
    owner: root
    group: root
    mode: 600

- name: Copy managevpn script
  copy:
    src: managevpn.sh
    dest: /usr/local/sbin/managevpn.sh
    owner: root
    group: root
    mode: 700

- name: Copy webinterface components
  when: webinterface_port is defined
  copy:
    src: ui/
    dest: /usr/local/vpn_webui
    owner: root
    group: root
    mode: 700

- name: Install webinterface
  when: webinterface_port is defined
  npm:
    name: /usr/local/vpn_webui
    path: /usr/local/vpn_webui

- name: Copy webinterface launch script
  when: webinterface_port is defined
  template:
    src: scripts/launchVPNWebinterface.sh.j2
    dest: /usr/local/sbin/launchVPNWebinterface.sh
    owner: root
    group: root
    mode: 700

- name: Copy hardware interface control
  when: enable_hw_interface
  copy:
    src: VPNControl.py
    dest: /usr/local/sbin/VPNControl.py
    owner: root
    group: root
    mode: 700

- name: Copy hardware interface launch script
  when: enable_hw_interface
  copy:
    src: launchVPNControl.sh
    dest: /usr/local/sbin/launchVPNControl.sh
    owner: root
    group: root
    mode: 700
